version: '3.7'

services:
  mreys-net:
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: mreys-net
    restart: always
    volumes:
      - ./src:/app
      - /app/node_modules
    networks:
      - docker-nginx_proxy-network

networks:
  docker-nginx_proxy-network:
    external: true