export { default as HomePage } from './HomePage'
export { default as IdeasPage } from './IdeasPage'
export { default as OthersPage } from './OthersPage'
export { default as ProfilePage } from './ProfilePage'
export { default as TalkPage } from './TalkPage'